language: java

jdk:
- oraclejdk7
- oraclejdk8
node_js:
- 4.8.3
install: true

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
#  - npm install
  - npm install bower
  - node -v
  - npm -v
  - bower -v

script: mvn clean install
