language: java

jdk:
- oraclejdk7
- oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - cat ~/.m2/settings.xml
  - rm ~/.m2/settings.xml

script: mvn clean install
