language: java

jdk:
- oraclejdk7
- oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - npm update -g npm@latest
  - npm -v

script: mvn clean install
