language: java

sudo: false

jdk:
- oraclejdk7

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

script: mvn clean install
