language: java

#jdk:
#- oraclejdk7
#- oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java7-installer

node_js:
- 4.8.3
install: true

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - . $HOME/.nvm/nvm.sh
  - nvm install v7.7.1
  - nvm ls
  - nvm use 7
  - npm install -g bower
  - node -v
  - npm -v
  - bower -v

script: mvn clean install
